config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  resources :photos, only: [:index, :show]

  namespace :admin do
    resources :contacts do
      collection do
        get 'remove_all'
      end
    end


    resources :photos do
      get :autocomplete_category_title, on: :collection
      get :autocomplete_tag_title, on: :collection
    end

    resources :tags
    resources :categories
    root to: "photos#index"
  end
  match '/hidden', to: 'photos#hidden', via: 'get', :as => 'hidden'
  match '/contacts/new', to: 'contacts#create', via: 'post'
  resources 'contacts', only: [:new, :create]
  get '/about', to: 'welcome#about'

end

app/models/photo.rb
class Photo < ApplicationRecord
  has_many :photo_taggings
  has_many :children, :class_name => "Photo", foreign_key: "parent_id"
  belongs_to :parent, :class_name => "Photo"
  has_many :tags, through: :photo_taggings, dependent: :destroy

  has_many :photo_categories
  has_many :categories, through: :photo_categories, dependent: :destroy

  has_attached_file :image,
                    default_url: 'header.jpg',
                    styles: {
                      thumbnail: '600x460^',
                      original: '1900x1400^'
                    },
                    convert_options: {
                      original: '-quality 75 -strip'
                    }

  validates_attachment :image, content_type: { content_type: ['image/jpeg', 'image/gif', 'image/png'] }

  attr_accessor :remove_featured_image

  before_save :delete_featured_image, if: -> { remove_featured_image == '1' && !image_updated_at_changed? }


  def all_tags=(titles)
    self.tags = titles.first.split(',').map(&:strip).reject(&:empty?) .map do |title|
      Tag.where(title: title.strip).first_or_create! if title != ' '
    end
  end

  def all_tags
    tags.map(&:title).join(', ')
  end

  def all_categories=(titles)
    self.categories = titles.first.split(',').map(&:strip).reject(&:empty?) .map do |title|
      Category.where(title: title.strip).first_or_create! if title != ' '
    end
  end

  def all_categories
    categories.map(&:title).join(', ')
  end

  def self.tagged_with(title)
    Tag.find_by_title!(title).photos
  end

  def self.categorised_with(title)
    Category.find_by_title!(title).photos
  end
  private

  def delete_featured_image
    self.image = nil
  end
end

app/controllers/admin/photos_controller.rb
module Admin
  class PhotosController < Admin::ApplicationController
    autocomplete :tag, :title, full: true
    autocomplete :category, :title, full: true

    def index
      @photos = Photo.order(created_at: :desc)
    end

    def edit
      @photo = Photo.find(params[:id])
      @all_photos = Photo.where.not(id: @photo.id).where("parent_id IS NULL")
    end

    def new
      @photo = Photo.new
      render "edit"
    end

    def update
      if params[:id]
        @photo = Photo.find(params[:id])
        @photo.update_attributes(photo_params)
        flash[:notice] = 'Photo has been saved successfully.'
        redirect_to edit_admin_photo_path(@photo)
        raise ActiveRecord::RecordNotFound, "Photo not found" if @photo.nil?
      else
        @photo = Photo.find(params[:id])
      end

    end

    def create
      @photo = Photo.create(photo_params)
      if @photo.save
        flash[:notice] = 'Photo has been created successfully.'
        redirect_to edit_admin_photo_path(@photo)
      else
        render 'edit'
      end
    end

    def destroy
      @photo = Photo.find(params[:id])
      @photo.destroy
      flash[:notice] = 'Photo destroyed.'
      redirect_to admin_photos_path
    end

    private
    
    def photo_params
      params.require(:photo).permit(:title, :caption, :order, :link, :image, :in_slider, :parent_id, all_tags: [], all_categories: [])
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    @photos = {}
    if entry_params[:cat]
      cat = Category.find_by('title': entry_params[:cat])
      @photos = cat.photos
    end
    if entry_params[:tag]
      tag = Tag.find_by('title': entry_params[:tag])
      photos = tag.photos
      @photos = @photos.present? ? @photos.merge(photos) : photos
    end
    if !entry_params[:tag] && !entry_params[:cat]
      @photos = Photo.joins(:categories).where( categories: { hidden: [nil, "0"] }).where("parent_id IS NULL").order(order: :asc)
      if !primary_domain
        @photos = Photo.joins(:categories).where( categories: { hidden: 1 }).where.not(:title => "avatar_brenda").where.not(:title => "avatar_luciana").where("parent_id IS NULL").order(order: :asc)
      end
    end
  end
  def show
    @photo = Photo.find(params[:id])
  end
  def entry_params
    params.permit(:cat, :tag, :hidden)
  end
end

app/views/admin/photos/_tree.haml
%table.table.table-hover.table-condensed
  %thead
    %tr
      %th.d-none.d-sm-table-cell
      %th Title
      %th.d-none.d-sm-table-cell Categories
      %th.d-none.d-sm-table-cell Tags
      %th{colspan: 2}
        = "Actions"

  %tbody
    -photos.each_with_index do |photo, index|
      %tr{id: "photo_#{photo.id}", class: ""}
        %td.p-0.w-3
          .fixed-ratio
            = link_to edit_admin_photo_path(photo), class: "fixed-ratio__inner" do
              = image_tag photo.image(:thumbnail), class: 'w-100'
        %td
          = link_to photo.title, edit_admin_photo_path(photo)
        %td.d-none.d-sm-table-cell
          - if photo.categories.present?
            %ul.list-unstyled.flex.flex-row-wrap
              - photo.categories.each do |category|
                %li.mr-1
                  %i
                    = link_to edit_admin_category_path(category) do
                      = category.title
                      - if photo.categories.length > 1
                        = ","
        %td.d-none.d-sm-table-cell
          - if photo.tags.present?
            %ul.list-unstyled.flex.flex-row-wrap
              - photo.tags.each do |tag|
                %li.mr-1
                  %i
                    = link_to edit_admin_tag_path(tag) do
                      = tag.title

                      - if photo.tags.length > 1
                        = ","

        %td.text-right.text-nowrap
          = link_to edit_admin_photo_path(photo), class: "btn btn-outline-success btn-sm" do
            %span.glyphicon.glyphicon-ok{"aria-hidden" => "true"}
            = fa_icon "pencil"

          = link_to admin_photo_path(photo), :method=> :delete, class: "btn btn-outline-danger btn-sm", data: {confirm: "You sure to delete this photo?"} do
            %span.glyphicon.glyphicon-remove{"aria-hidden" => "true"}
            = fa_icon "remove"
        %td.text-right.text-nowrap.d-flex.flex-column
          - if photo.parent.present?
            -#= link_to edit_admin_photo_path(photo.parent), class: "" do
              -#= "##{ photo.parent.id }"
              -#= photo.parent.title
            .fixed-ratio
              = link_to edit_admin_photo_path(photo.parent), class: "fixed-ratio__inner" do
                = image_tag photo.parent.image(:thumbnail), class: 'w-100'

app/views/admin/photos/edit.haml
- if action_name == "new"
  - path = admin_photos_path
- else
  - path = admin_photo_path(@photo)

= form_for(@photo, url: path, :html =>{class: ""}) do |f|
  %h3
    - if action_name == "new"
      New Photo
    - else
      ="#{@photo.title} - Id ##{@photo.id}"
    %small= f.submit "Update", class: "ml-2 btn btn-primary float-right", disabled: false
  .row
    .col-md-4
      .form-group
        - unless action_name == "new"
          = image_tag(@photo.image, class: "img-fluid")
        %label{:for => "image"}
        = f.file_field :image

    .col-md-8
      .row
        .col-md-6
          .form-group
            %label{:for => "title"} Title
            = f.text_field :title, placeholder: "Title", class: "form-control"
          .form-group
            %label{:for => "in_slider"}
              Sliderposition
            = link_to "#", "data-content" => "If there is just one image defined with sliderposition it will display without slider functionality but as fullscreen header image. If you define  more than one image as a sliderimage, the slider is active, the right-left buttons and the small bottom navigation appear.", "data-toggle" => "popover", "data-trigger" => "focus" , :title => "How the slider works." do
              = fa_stacked_icon "info inverse", base: "circle", class: ""


              %small 
            = f.number_field :in_slider, placeholder: "1-99", class: "form-control"
          .form-group
            %label{:for => "parent_id"}
              Parent Id
            = link_to "#", "data-content" => "Images which have a parent id are children from a Masterimage. That means one Masterimage can have many children which have all the same parent_id.", "data-toggle" => "popover", "data-trigger" => "focus" , :title => "Parent/Child association" do
              = fa_stacked_icon "info inverse", base: "circle", class: ""
            .input-group
              = f.text_field :parent_id, placeholder: "ID", class: "form-control"
              .input-group-append
                %button.btn.btn-primary{"data-target" => "#exampleModal", "data-toggle" => "modal", :type => "button"}
                  Select parent Photo
        .col-md-6
          .form-group
            .field-unit__label
              = f.label :all_categories
            .field-unit__field
              %div#category_input

                = f.autocomplete_field :all_categories,
                autocomplete_category_title_admin_photos_path,
                "data-role" => "categoriesinput",
                placeholder: "Categories separated with comma",
                class: "form-control",
                'data-delimiter' => ', ',
                :multiple => true,
                :append_to => "#category_input",
                'data-auto-focus' => true

          .form-group
            .field-unit__label
              = f.label :all_tags
            .field-unit__field
              %div#tag_input

                = f.autocomplete_field :all_tags,
                autocomplete_tag_title_admin_photos_path,
                "data-role" => "tagsinput",
                placeholder: "Tags separated with comma",
                class: "form-control",
                'data-delimiter' => ', ',
                :multiple => true,
                :append_to => "#tag_input",
                'data-auto-focus' => true

          .form-group
            %label{:for => "link"} Link
            = f.text_field :link, placeholder: "Link", class: "form-control"
      .form-group
        %label{:for => "caption"} Caption
        = f.text_area :caption, placeholder: "Caption name", class: "form-control"



  - if action_name != "new"
    = link_to "Show", photo_path(@photo), class: "btn btn-secondary float-right" 
  = f.submit "Update", class: "btn btn-primary float-right", disabled: false




#exampleModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title Modal title
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        .row
          - if @all_photos.present?
            - @all_photos.each do |photo|
              .col-md-3.col-sm-6
                = link_to edit_admin_photo_path(photo), class: "fixed-ratio__inner" do
                  = image_tag photo.image(:thumbnail), class: 'w-100 parentselector ', "data-photo-id": photo.id

      .modal-footer
        %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Close
        %button.btn.btn-primary{:type => "button"} Save changes

app/views/admin/photos/index.haml
%h3
  Photos
  = link_to "New photo", new_admin_photo_path, class: "btn btn-primary mb-3 float-right"
%table.table.table-hover.table-condensed
  %thead
    %tr
      %th #
      %th Image
      %th Sliderpos
      %th Title
      %th Cats
      %th Tags
      %th Parent
      %th{colspan: 2}
        = "Actions"

  %tbody
    -@photos.each_with_index do |photo, index|
      %tr{id: "photo_#{photo.id}", class: ""}
        %td
          = photo.id
        %td.p-0.w-3
          .fixed-ratio
            = link_to edit_admin_photo_path(photo), class: "fixed-ratio__inner" do
              = image_tag photo.image(:thumbnail), class: 'w-100'
        %td
          = link_to admin_photos_path do
            = photo.in_slider
        %td
          = link_to photo.title, edit_admin_photo_path(photo)

        %td.d-none.d-sm-table-cell
          - if photo.categories.present?
            %ul.list-unstyled.flex.flex-row-wrap
              - photo.categories.each do |category|
                %li.mr-1
                  %i
                    = link_to edit_admin_category_path(category) do
                      = category.title
                      - if photo.categories.length > 1
                        = ","
        %td.d-none.d-sm-table-cell
          - if photo.tags.present?
            %ul.list-unstyled.flex.flex-row-wrap
              - photo.tags.each do |tag|
                %li.mr-1
                  %i
                    = link_to edit_admin_tag_path(tag) do
                      = tag.title

                      - if photo.tags.length > 1
                        = ","


        %td.text-right.text-nowrap.d-flex.flex-column
          - if photo.parent.present?
            -#= link_to edit_admin_photo_path(photo.parent), class: "" do
              -#= "##{ photo.parent.id }"
              -#= photo.parent.title
            .fixed-ratio
              = link_to edit_admin_photo_path(photo.parent), class: "fixed-ratio__inner" do
                = image_tag photo.parent.image(:thumbnail), class: 'w-100'

        %td.text-right.text-nowrap
          = link_to edit_admin_photo_path(photo), class: "btn btn-outline-success btn-sm" do
            %span.glyphicon.glyphicon-ok{"aria-hidden" => "true"}
            = fa_icon "pencil"

          = link_to admin_photo_path(photo), :method=> :delete, class: "btn btn-outline-danger btn-sm", data: {confirm: "You sure to delete this photo?"} do
            %span.glyphicon.glyphicon-remove{"aria-hidden" => "true"}
            = fa_icon "remove"