config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  resources :photos, only: [:index, :show]

  namespace :admin do
    resources :contacts do
      collection do
        get 'remove_all'
      end
    end


    resources :photos do
      get :autocomplete_category_title, on: :collection
      get :autocomplete_tag_title, on: :collection
    end

    resources :tags
    resources :categories
    root to: "photos#index"
  end
  match '/hidden', to: 'photos#hidden', via: 'get', :as => 'hidden'
  match '/contacts/new', to: 'contacts#create', via: 'post'
  resources 'contacts', only: [:new, :create]
  get '/about', to: 'welcome#about'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  
end

app/controllers/admin/contacts_controller.rb
module Admin
  class ContactsController < ApplicationController

    def index
      @contacts = Contact.all.reverse
    end
    
    def destroy
      @contact = Contact.find(params[:id])
      @contact.destroy
      flash[:notice] = 'Contact destroyed.'
      redirect_to admin_contacts_path
    end

    def remove_all
      Contact.delete_all
      flash[:notice] = "You have removed all contact!"
      redirect_to admin_contacts_path
    end

  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  puts request.inspect
    @contact = Contact.new
    @page_title = "#{@page_title} | Contact"
  end

  def create
    mail = Mailer.new(allowed_params)
    mail.request = request
    if mail.deliver
      flash.now[:notice] = 'Thank you for your message!'
      @contact = Contact.new(allowed_params)
      @contact.save
      respond_to do |format|
        format.html { redirect_to contacts_path }
        format.js
      end
    else
      flash.now[:error] = 'Cannot send message.'
    end
  end


  def allowed_params
    params.require(:contact).permit(:email, :message, :nickname)
  end

end

app/views/admin/contacts/index.haml
%h3 Contacts
%table.table.table-hover.table-condensed.table-responsive
  %thead
    %tr
      %th Message
      %th Email
      %th Date
      %th{colspan: 2}
        = "Actions"

  %tbody
    -@contacts.each_with_index do |contact, index|
      %tr{id: "contact_#{contact.id}", class: ""}
        %td
          = contact.message
        %td
          = contact.email
        %td
          = contact.created_at

        %td.text-right.text-nowrap
          -#= link_to edit_admin_contact_path(contact), class: "btn btn-outline-success btn-sm" do
            -#%span.glyphicon.glyphicon-ok{"aria-hidden" => "true"}
            -#= fa_icon "pencil"

          = link_to admin_contact_path(contact), :method=> :delete, class: "btn btn-outline-danger btn-sm", data: {confirm: "You sure to delete this contact?"} do
            %span.glyphicon.glyphicon-remove{"aria-hidden" => "true"}
            = fa_icon "remove"
- if @contacts.any?
  = link_to "Remove All", remove_all_admin_contacts_path, :method => :get, class: "btn btn-danger", data: {confirm: "This will clear this list. I hope you recieved all emails and answered thos people."}