config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  resources :photos, only: [:index, :show]

  namespace :admin do
    resources :contacts do
      collection do
        get 'remove_all'
      end
    end


    resources :photos do
      get :autocomplete_category_title, on: :collection
      get :autocomplete_tag_title, on: :collection
    end

    resources :tags
    resources :categories
    root to: "photos#index"
  end
  match '/hidden', to: 'photos#hidden', via: 'get', :as => 'hidden'
  match '/contacts/new', to: 'contacts#create', via: 'post'
  resources 'contacts', only: [:new, :create]
  get '/about', to: 'welcome#about'

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :photo_categories
  has_many :photos, through: :photo_categories, dependent: :destroy
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < Admin::ApplicationController

    def index
      @categories = Category.left_joins(:photos)
        .group(:id)
        .order('COUNT(photos.id) DESC')
        .limit(10)
    end

    def edit
      @category = Category.find(params[:id])
    end

    def new
      @category = Category.new
      render "edit"
    end

    def update
      if params[:id]
        @category = Category.find(params[:id])
        @category.update_attributes(category_params)
        flash[:notice] = 'Category has been saved successfully.'
        redirect_to edit_admin_category_path(@category)
        raise ActiveRecord::RecordNotFound, "Category not found" if @category.nil?
      else
        @category = Category.find(params[:id])
      end

    end

    def create
      @category = Category.create(category_params)
      if @category.save
        flash[:notice] = 'Category has been created successfully.'
        redirect_to edit_admin_category_path(@category)
      else
        render 'edit'
      end
    end

    def destroy
      @category = Category.find(params[:id])
      @category.destroy
      flash[:notice] = 'Category destroyed.'
      redirect_to admin_categories_path
    end

    private

    def category_params
      params.require(:category).permit(:title, :hidden)
    end
  end
end

app/views/admin/categories/edit.html.haml
- if action_name == "new"
  - path = admin_categories_path
- else
  - path = admin_category_path(@category)

= form_for(@category, url: path, :html =>{class: ""}) do |f|
  %h3
    - if action_name == "new"
      New category
    - else
      ="Category: #{@category.title} "
    %small= f.submit "Update", class: "ml-2 btn btn-primary float-right", disabled: false

  .form-group
    %label{:for => "title"} Title
    = f.text_field :title, placeholder: "Title", class: "form-control"
  .form-group
    %label{:for => "hidden"} Hidden
    = f.check_box :hidden


  .form-group.text-right
    = f.submit "Update", class: "btn btn-primary ", disabled: false

- if @category.photos
  %h3 Photos with this category:
  = render "admin/photos/tree", photos: @category.photos

app/views/admin/categories/index.haml
%h3
  Categories
  = link_to "New Category", new_admin_category_path, class: "btn btn-primary mb-3 float-right"
%table.table.table-hover.table-condensed
  %thead
    %tr
      %th Title
      %th Photos
      %th Hidden?
      %th.text-right{colspan: 2}
        = "Actions"

  %tbody
    -@categories.each_with_index do |category, index|
      %tr{id: "category_#{category.id}", class: ""}
        %td
          = link_to category.title, edit_admin_category_path(category)

        %td
          = category.photos.count
        %td
          - if category.hidden?
            yes


        %td.text-right.text-nowrap
          = link_to edit_admin_category_path(category), class: "btn btn-outline-success btn-sm" do
            %span.glyphicon.glyphicon-ok{"aria-hidden" => "true"}
            = fa_icon "pencil"

          = link_to admin_category_path(category), :method=> :delete, class: "btn btn-outline-danger btn-sm", data: {confirm: "You sure to delete this category?"} do
            %span.glyphicon.glyphicon-remove{"aria-hidden" => "true"}
            = fa_icon "remove"