config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  resources :photos, only: [:index, :show]

  namespace :admin do
    resources :contacts do
      collection do
        get 'remove_all'
      end
    end


    resources :photos do
      get :autocomplete_category_title, on: :collection
      get :autocomplete_tag_title, on: :collection
    end

    resources :tags
    resources :categories
    root to: "photos#index"
  end
  match '/hidden', to: 'photos#hidden', via: 'get', :as => 'hidden'
  match '/contacts/new', to: 'contacts#create', via: 'post'
  resources 'contacts', only: [:new, :create]
  get '/about', to: 'welcome#about'

end

app/views/admin/shared/_image_grid.html.haml
- if @images
  - @images.each do |image|
    .col-md-3.col-4.mb-3{id: "image_#{image.id}"}
      .fixed-ratio--1-to-1
        -#= image_tag(image.url)
        = image_tag(image.image, class: "imagepicker fixed-ratio__inner", "data-image-id" => image.id)
        = link_to admin_post_image_path(image), :method=> :delete, class: "btn btn-danger btn-sm position-absolute top-right", remote: true, data: {confirm: "You sure to delete this image?"} do
          = fa_icon "remove"

app/views/admin/shared/_media_library.html.haml
#imageModal.modal{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-lg{:role => "document"}
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title.text-dark All Images
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          = fa_icon "times"

      .modal-body 
        #image_grid.row
          = render "admin/shared/image_grid"
          -#.image_remover.card.py-5.text-center
            -#=fa_icon "remove"

      .modal-footer
        = form_tag admin_post_images_path(:post_id => @post.id), format: :js, remote: true,  class: "form-inline w-100 flex-nowrap" do
          .form-group.flex-grow.mr-2.text-dark
            = file_field_tag :post_image, required: true
          .form-group
            = submit_tag "Upload", :name => nil, class: "btn btn-primary"
        = form_tag admin_upload_from_url_path(:post_id => @post.id), remote: true,  class: "form-inline w-100" do
          .form-group.flex-grow.mr-2
            = search_field_tag :image_url, params[:image_url], autofocus: true, :placeholder => "http://", class: "form-control flex-grow"
          .form-group
            = submit_tag "Upload", :name => nil, class: "btn btn-primary"
            -#%button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Close
        -#%button.btn.btn-primary{:type => "button"} Save changes

app/views/admin/shared/_navigation.haml
%nav.navbar.navbar-expand-md.navbar-dark.navbar-inverse.flex-md-column.align-items-start.bg-inverse
  = link_to root_path, class: "navbar-brand" do
    Frontend
  %button.navbar-toggler{"aria-controls" => "navbarNavAltMarkup", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNavAltMarkup", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarNavAltMarkup.collapse.navbar-collapse.align-items-start
    .navbar-nav.flex-md-column
    
      = link_to admin_photos_path, class: "#{controller_name == "photos" ? "active" : ""} nav-item nav-link px-0" do
        Photos

      = link_to admin_tags_path, class: "#{controller_name == "tags" ? "active" : ""} nav-item nav-link px-0" do
        Tags
    
      = link_to admin_categories_path, class: "#{controller_name == "categories" ? "active" : ""} nav-item nav-link px-0" do
        Categories
    
      = link_to admin_contacts_path, class: "#{controller_name == "contacts" ? "active" : ""} nav-item nav-link px-0" do
        Contacts
        - if @contacts.any?
          %span.badge.badge-danger= @contacts.count
    
      = link_to destroy_user_session_path, :method => :delete, class: 'nav-item nav-link px-0', title: "logout" do
        Logout